### ISSUE TITLE
Some servers missing (Only one here)

### ISSUE THREAD

**Issue by amysthat** [Koupah/Valorant-Ranked-Checker#1]
Ummm, this is pretty short but...

You have Turkey servers missing.

That's all.

**Comment by Koupah** [comment]
Thanks for opening this issue, however you should be able to use the "Asia" server to log in.
If this works please get back to me and I'll add in "Turkey" to the list to use the Asian server, otherwise I'll further search for the correct api url.

Edit: Just noticed, no log ins would work due to an issue. Update to the latest version (of which I am about to release) then let me know about the above! Thank you
